import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const dir = await mkdtemp(path.join(tmpdir(), 'compressor-ui-'));
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const ff = args => execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args]);
const settled = () => page.waitForFunction(() => !document.querySelector('#play').disabled && [...document.querySelectorAll('.status')].every(e => !e.textContent || e.textContent === 'Still preview'));
const slider = (selector, value, change = false) => page.locator(selector).first().evaluate((el, { value, change }) => { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); if (change) el.dispatchEvent(new Event('change', { bubbles: true })); }, { value, change });
try {
  await page.goto(process.env.APP_URL);
  assert.equal(await page.locator('footer, #replace, .local, #zoom').count(), 0);
  await page.screenshot({ path: '/tmp/compressor-empty.png' });
  ff(['-f', 'lavfi', '-i', 'testsrc2=size=960x640', '-frames:v', '1', path.join(dir, 'image.png')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'image.png'));
  await page.waitForSelector('.original img'); await settled();
  assert.equal(await page.locator('.card').count(), 4);
  assert.ok(await page.locator('.card').first().evaluate(el => el.classList.contains('original')));
  assert.equal(await page.locator('[data-key="format"] option[value="png"]').count(), 0);
  await slider('[data-key="quality"]', '32'); await settled();
  await slider('[data-key="resolution"]', '50'); await settled();
  assert.equal(await page.locator('.card:not(.original) img').first().evaluate(el => el.naturalWidth), 480);
  const crop = await page.locator('.detail canvas').first().evaluate(el => el.toDataURL());
  await page.locator('.preview').first().hover({ position: { x: 50, y: 50 } });
  assert.equal(await page.locator('.detail canvas').first().evaluate(el => el.toDataURL()), crop);
  assert.ok((await page.locator('.detail').first().boundingBox()).height >= 250);
  await page.screenshot({ path: '/tmp/compressor-image.png' });
  await page.locator('#add').click(); assert.equal(await page.locator('.card').count(), 5);
  await page.locator('.remove').last().click(); assert.equal(await page.locator('.card').count(), 4); await settled();
  const download = page.waitForEvent('download'); await page.locator('.export').first().click(); assert.match((await download).suggestedFilename(), /\.webp$/);
  ff(['-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=24', '-t', '6', '-c:v', 'libx264', path.join(dir, 'video.mp4')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'video.mp4'));
  await page.waitForSelector('.original video'); await settled();
  assert.equal(await page.locator('video').count(), 4);
  const ratio = await page.locator('.preview').first().evaluate(el => el.clientWidth / el.clientHeight); assert.ok(Math.abs(ratio - 640 / 360) < .02);
  assert.equal(await page.locator('[data-key="bitrate"]').first().getAttribute('type'), 'range');
  assert.match(await page.locator('.bitrate-output').first().textContent(), /800 kbps/);
  console.log('Video ready'); await page.locator('#play').click(); await page.waitForTimeout(550);
  assert.ok(Number(await page.locator('#time').inputValue()) > .2);
  async function checkSync() { const times = await page.locator('video').evaluateAll(vs => vs.map(v => v.currentTime)); assert.ok(Math.max(...times) - Math.min(...times) < .15, JSON.stringify(times)); }
  await checkSync();
  // Delay one preview to reproduce staggered encoder completion while playing.
  await page.route('**/api/preview', async route => { if (route.request().postDataJSON().bitrate === 6000) await new Promise(r => setTimeout(r, 1200)); await route.continue(); });
  await slider('[data-key="bitrate"]', '500');
  await page.waitForTimeout(500);
  assert.ok(await page.locator('video').evaluateAll(vs => vs.every(v => v.paused)));
  await settled(); await page.waitForTimeout(400); await checkSync();
  await page.unroute('**/api/preview');
  console.log('Delayed responses synchronized'); await slider('#duration', '4'); await settled();
  assert.equal(await page.locator('#duration-label').textContent(), '4 s');
  await page.waitForTimeout(450); await checkSync();
  console.log('Duration ready'); await slider('#time', '1.5', true); await page.waitForTimeout(300); await checkSync();
  await page.waitForFunction(() => Number(document.querySelector('#time').value) > 1.6, { timeout: 5000 });
  console.log('Seek resumed'); await slider('#time', '4.5', true); await settled(); await page.waitForTimeout(350); await checkSync();
  assert.ok(Number(await page.locator('#time').inputValue()) >= 4.5);
  await page.waitForTimeout(1800); await checkSync();
  await page.locator('[data-key="format"]').first().selectOption('hevc'); await settled(); assert.equal(await page.locator('video').count(), 4); await page.waitForTimeout(200); await checkSync();
  await page.locator('[data-key="format"]').nth(1).selectOption('avc'); await settled();
  await page.waitForTimeout(200); await page.screenshot({ path: '/tmp/compressor-video.png' });
  ff(['-f', 'lavfi', '-i', 'sine=frequency=600', '-t', '9', path.join(dir, 'audio.wav')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'audio.wav'));
  await page.waitForSelector('.original audio', { state: 'attached' }); await settled();
  assert.equal(await page.locator('.card').count(), 2);
  assert.equal(await page.locator('.bitrate-output').textContent(), '256 kbps');
  assert.equal(await page.locator('[data-key="format"]').inputValue(), 'mp3');
  await slider('[data-key="bitrate"]', '500'); await settled();
  await page.locator('[data-key="format"]').selectOption('opus'); await settled();
  await page.locator('.listen').last().click(); await page.waitForTimeout(300);
  assert.equal(await page.locator('audio').last().evaluate(el => el.muted), false);
  assert.equal(await page.locator('audio').first().evaluate(el => el.muted), true);
  await page.screenshot({ path: '/tmp/compressor-audio.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: '/tmp/compressor-mobile.png' });
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: original, fixed detail, sliders, synchronized loading/playback/seeking/looping, duration, export, audio comparison, and mobile.');
} catch (e) { console.error(await page.evaluate(() => ({ button: document.querySelector('#play').textContent, error: document.querySelector('#error').textContent, time: document.querySelector('#time').value, media: [...document.querySelectorAll('video')].map(m => ({ t: m.currentTime, paused: m.paused, seeking: m.seeking, ready: m.readyState, duration: m.duration })) }))); throw e; } finally { await browser.close(); await rm(dir, { recursive: true, force: true }); }
