import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
const dir = await mkdtemp(path.join(tmpdir(), 'compressor-ui-'));
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
let previewRequests = 0;
page.on('request', request => { if (new URL(request.url()).pathname === '/api/preview') previewRequests++; });
const ff = args => execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', ...args]);
const settled = () => page.waitForFunction(() => !document.querySelector('#play').disabled && [...document.querySelectorAll('.status')].every(e => !e.textContent || e.textContent === 'Still preview'));
const slider = (selector, value, change = false) => page.locator(selector).first().evaluate((el, { value, change }) => { el.value = value; el.dispatchEvent(new Event('input', { bubbles: true })); if (change) el.dispatchEvent(new Event('change', { bubbles: true })); }, { value, change });
try {
  await page.goto(process.env.APP_URL);
  assert.equal(await page.locator('footer, #replace, .local, #zoom').count(), 0);
  await page.screenshot({ path: '/tmp/compressor-empty.png' });
  ff(['-f', 'lavfi', '-i', 'testsrc2=size=960x640', '-frames:v', '1', path.join(dir, 'image.png')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'image.png'));
  await page.waitForSelector('.original img'); await settled();
  assert.equal(await page.locator('.card').count(), 4);
  assert.ok(await page.locator('.card').first().evaluate(el => el.classList.contains('original')));
  assert.equal(await page.locator('[data-key="format"] option[value="png"]').count(), 0);
  await slider('[data-key="quality"]', '32'); await settled();
  await slider('[data-key="resolution"]', '50'); await settled();
  assert.equal(await page.locator('.card:not(.original) img').first().evaluate(el => el.naturalWidth), 480);
  const crop = await page.locator('.detail canvas').first().evaluate(el => el.toDataURL());
  await page.locator('.preview').first().hover({ position: { x: 50, y: 50 } });
  assert.equal(await page.locator('.detail canvas').first().evaluate(el => el.toDataURL()), crop);
  assert.ok((await page.locator('.detail').first().boundingBox()).height >= 250);
  await page.screenshot({ path: '/tmp/compressor-image.png' });
  assert.equal(await page.locator('.remove').count(), 3);
  assert.equal(await page.locator('#cards > #add:last-child svg').count(), 1);
  const addBox = await page.locator('#add').boundingBox();
  const lastBox = await page.locator('.card').last().boundingBox();
  const iconBox = await page.locator('#add svg').boundingBox();
  assert.ok(addBox.x >= lastBox.x + lastBox.width);
  assert.ok(Math.abs(iconBox.x + iconBox.width / 2 - addBox.x - addBox.width / 2) < 1);
  assert.ok(Math.abs(iconBox.y + iconBox.height / 2 - addBox.y - addBox.height / 2) < 1);
  assert.equal(await page.locator('.paste-settings:disabled').count(), 3);
  const copiedImageUrl = await page.locator('.card:not(.original) img').first().getAttribute('src');
  await page.locator('.copy-settings').first().click();
  await slider('[data-key="quality"]', '60'); await settled();
  const beforeImagePaste = previewRequests;
  await page.locator('.paste-settings').nth(1).click(); await settled();
  assert.equal(previewRequests, beforeImagePaste, 'Image paste should reuse cached previews without render requests');
  assert.equal(await page.locator('.card:not(.original) img').nth(1).getAttribute('src'), copiedImageUrl);
  assert.deepEqual(await page.locator('.card:not(.original) .detail canvas').nth(1).evaluate(el => ({ enabled: el.getContext('2d').imageSmoothingEnabled, quality: el.getContext('2d').imageSmoothingQuality, rendering: getComputedStyle(el).imageRendering })), { enabled: true, quality: 'high', rendering: 'auto' });
  assert.equal(await page.locator('[data-key="quality"]').nth(1).inputValue(), '32');
  assert.equal(await page.locator('[data-key="resolution"]').nth(1).inputValue(), '50');
  assert.equal(await page.locator('[data-key="quality"]').first().inputValue(), '60');
  assert.equal(await page.locator('.card:not(.original) img').nth(1).evaluate(el => el.naturalWidth), 480);
  await page.locator('[data-key="format"]').nth(1).selectOption('jpeg'); await settled();
  await page.locator('.paste-settings').nth(2).click(); await settled();
  assert.equal(await page.locator('[data-key="format"]').nth(2).inputValue(), 'webp');
  await page.locator('#add').click(); await settled();
  assert.equal(await page.locator('.card').count(), 5);
  assert.equal(await page.locator('.paste-settings').last().isEnabled(), true);
  assert.equal(await page.locator('#cards > #add:last-child').count(), 1);
  await page.locator('.remove').last().click(); await settled();
  assert.equal(await page.locator('.card').count(), 4);
  await page.reload(); await page.waitForSelector('.original img'); await settled();
  assert.equal(await page.locator('#file-name').textContent(), 'image.png');
  assert.equal(await page.locator('.card').count(), 4);
  assert.equal(await page.locator('[data-key="quality"]').first().inputValue(), '60');
  assert.equal(await page.locator('[data-key="format"]').nth(1).inputValue(), 'jpeg');
  assert.equal(await page.locator('[data-key="resolution"]').nth(2).inputValue(), '50');
  assert.equal(await page.locator('.paste-settings:enabled').count(), 3);
  await page.locator('.paste-settings').first().click(); await settled();
  assert.equal(await page.locator('[data-key="quality"]').first().inputValue(), '32');
  const download = page.waitForEvent('download'); await page.locator('.export').first().click(); assert.match((await download).suggestedFilename(), /\.webp$/);
  // Resolution locks synchronize edits, pastes and newly added previews, and survive reload.
  assert.equal(await page.locator('[data-lock="bitrate"]').count(), 0);
  await page.locator('[data-lock="resolution"]').first().click(); await settled();
  assert.equal(await page.locator('[data-lock="resolution"][aria-pressed="true"]').count(), 3);
  await slider('[data-key="resolution"]', '75'); await settled();
  assert.deepEqual(await page.locator('[data-key="resolution"]').evaluateAll(inputs => inputs.map(i => i.value)), ['75', '75', '75']);
  assert.deepEqual(await page.locator('.card:not(.original) img').evaluateAll(images => images.map(i => i.naturalWidth)), [720, 720, 720]);
  assert.equal(await page.locator('.original img').evaluate(i => i.naturalWidth), 960);
  await page.locator('.paste-settings').nth(1).click(); await settled();
  assert.deepEqual(await page.locator('[data-key="resolution"]').evaluateAll(inputs => inputs.map(i => i.value)), ['50', '50', '50']);
  await page.locator('#add').click(); await settled();
  assert.equal(await page.locator('[data-lock="resolution"][aria-pressed="true"]').count(), 4);
  await page.reload(); await page.waitForSelector('.original img'); await settled();
  assert.equal(await page.locator('[data-lock="resolution"][aria-pressed="true"]').count(), 4);
  await page.locator('[data-lock="resolution"]').nth(1).click(); await settled();
  await slider('[data-key="resolution"]', '65'); await settled();
  assert.deepEqual(await page.locator('[data-key="resolution"]').evaluateAll(inputs => inputs.map(i => i.value)), ['65', '50', '50', '50']);
  ff(['-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=24', '-t', '6', '-c:v', 'libx264', path.join(dir, 'video.mp4')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'video.mp4'));
  await page.waitForSelector('.original video'); await settled();
  assert.equal(await page.locator('video').count(), 4);
  assert.equal(await page.locator('.paste-settings:disabled').count(), 3);
  assert.ok((await page.locator('#time').boundingBox()).width <= 180);
  const ratio = await page.locator('.preview').first().evaluate(el => el.clientWidth / el.clientHeight); assert.ok(Math.abs(ratio - 640 / 360) < .02);
  assert.equal(await page.locator('[data-key="bitrate"]').first().getAttribute('type'), 'range');
  assert.match(await page.locator('.bitrate-output').first().textContent(), /800 kbps/);
  // Space owns focused buttons, selects and sliders, including keyup and held keys.
  for (const selector of ['#add', '[data-key="format"]', '[data-key="bitrate"]', '#play']) {
    await page.locator(selector).first().focus();
    await page.keyboard.down('Space'); await page.keyboard.down('Space');
    await page.keyboard.up('Space');
    await page.waitForFunction(() => document.querySelector('#play').textContent.includes('Pause'));
    assert.equal(await page.locator('.card').count(), 4);
    await page.keyboard.press('Space');
    assert.match(await page.locator('#play').textContent(), /Play/);
  }
  console.log('Video ready'); await page.locator('#play').click(); await page.waitForTimeout(550);
  assert.ok(Number(await page.locator('#time').inputValue()) > .2);
  async function checkSync() { const times = await page.locator('video').evaluateAll(vs => vs.map(v => v.currentTime)); assert.ok(Math.max(...times) - Math.min(...times) < .15, JSON.stringify(times)); }
  await checkSync();
  // Delay one preview to reproduce staggered encoder completion while playing.
  await page.route('**/api/preview', async route => { if (route.request().postDataJSON().bitrate === 3200) await new Promise(r => setTimeout(r, 1200)); await route.continue(); });
  await slider('[data-key="bitrate"]', '500');
  await page.waitForTimeout(500);
  assert.ok(await page.locator('video').evaluateAll(vs => vs.every(v => v.paused)));
  await settled(); await page.waitForTimeout(400); await checkSync();
  assert.equal(await page.locator('.bitrate-output').first().textContent(), '3,200 kbps');
  await page.unroute('**/api/preview');
  const copiedVideoUrl = await page.locator('.card:not(.original) video').first().getAttribute('src');
  await page.locator('.copy-settings').first().click();
  const beforeVideoPaste = previewRequests;
  await page.locator('.paste-settings').nth(1).click(); await settled();
  assert.equal(previewRequests, beforeVideoPaste, 'Video paste should reuse cached previews without render requests');
  assert.equal(await page.locator('.card:not(.original) video').nth(1).getAttribute('src'), copiedVideoUrl);
  await page.waitForTimeout(300); await checkSync();
  const beforeDurationChange = previewRequests;
  console.log('Delayed responses synchronized'); await slider('#duration', '4'); await settled();
  assert.equal(previewRequests - beforeDurationChange, 3, 'Matching previews should share one render request for the new duration');
  assert.equal(await page.locator('#duration-label').textContent(), '4 s');
  await page.waitForTimeout(450); await checkSync();
  console.log('Duration ready'); await slider('#time', '1.5', true); await page.waitForTimeout(300); await checkSync();
  await page.waitForFunction(() => Number(document.querySelector('#time').value) > 1.6, { timeout: 5000 });
  console.log('Seek resumed'); await slider('#time', '4.5', true); await settled(); await page.waitForTimeout(350); await checkSync();
  assert.ok(Number(await page.locator('#time').inputValue()) >= 4.5);
  await page.waitForTimeout(1800); await checkSync();
  await page.locator('[data-key="format"]').first().selectOption('hevc'); await settled(); assert.equal(await page.locator('video').count(), 4); await page.waitForTimeout(200); await checkSync();
  await page.locator('[data-key="format"]').nth(1).selectOption('avc'); await settled();
  await page.waitForTimeout(200); await page.screenshot({ path: '/tmp/compressor-video.png' });
  assert.equal(await page.locator('[data-lock="resolution"][aria-pressed="true"]').count(), 0);
  await page.locator('[data-lock="bitrate"]').nth(2).click(); await settled();
  assert.deepEqual(await page.locator('.bitrate-output').allTextContents(), ['6,000 kbps', '6,000 kbps', '6,000 kbps']);
  await slider('[data-key="bitrate"]', '500'); await settled();
  assert.deepEqual(await page.locator('.bitrate-output').allTextContents(), ['3,200 kbps', '3,200 kbps', '3,200 kbps']);
  assert.equal(await page.locator('[data-lock="resolution"][aria-pressed="true"]').count(), 0);
  await page.screenshot({ path: '/tmp/compressor-locks.png' });
  ff(['-f', 'lavfi', '-i', 'sine=frequency=600', '-t', '9', path.join(dir, 'audio.wav')]);
  await page.locator('#file').setInputFiles(path.join(dir, 'audio.wav'));
  await page.waitForSelector('.original audio', { state: 'attached' }); await settled();
  assert.equal(await page.locator('.card').count(), 2);
  assert.equal(await page.locator('.bitrate-output').textContent(), '256 kbps');
  assert.equal(await page.locator('[data-key="format"]').inputValue(), 'mp3');
  await slider('[data-key="bitrate"]', '500'); await settled();
  await page.locator('[data-key="format"]').selectOption('opus'); await settled();
  await page.locator('.listen').last().click(); await page.waitForTimeout(300);
  assert.equal(await page.locator('audio').last().evaluate(el => el.muted), false);
  assert.equal(await page.locator('audio').first().evaluate(el => el.muted), true);
  await page.keyboard.press('Space');
  await slider('#duration', '3'); await settled();
  await slider('#time', '4.5', true); await settled();
  const savedPosition = Number(await page.locator('#time').inputValue());
  await page.reload(); await page.waitForSelector('.original audio', { state: 'attached' }); await settled();
  assert.equal(await page.locator('[data-key="format"]').inputValue(), 'opus');
  assert.equal(await page.locator('#duration').inputValue(), '3');
  assert.ok(Math.abs(Number(await page.locator('#time').inputValue()) - savedPosition) < .05);
  assert.equal(await page.locator('.listen').last().getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('audio').last().evaluate(el => el.muted), false);
  assert.match(await page.locator('#play').textContent(), /Play/);
  await page.keyboard.press('Space'); await page.waitForTimeout(200);
  await page.reload(); await page.waitForSelector('.original audio', { state: 'attached' }); await settled();
  await page.waitForFunction(() => [...document.querySelectorAll('audio')].every(m => !m.paused));
  await page.screenshot({ path: '/tmp/compressor-audio.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: '/tmp/compressor-mobile.png' });
  assert.equal(await page.locator('[data-lock="resolution"]').count(), 0);
  await page.locator('#add').click(); await settled();
  await page.locator('[data-key="format"]').last().selectOption('mp3'); await settled();
  await slider('[data-key="bitrate"]', '1000'); await settled();
  await page.locator('[data-lock="bitrate"]').first().click(); await settled();
  assert.deepEqual(await page.locator('.bitrate-output').allTextContents(), ['320 kbps', '320 kbps']);
  await slider('[data-key="bitrate"]', '500'); await settled();
  assert.deepEqual(await page.locator('.bitrate-output').allTextContents(), ['128 kbps', '128 kbps']);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: original, fixed detail, sliders, synchronized loading/playback/seeking/looping, duration, export, audio comparison, and mobile.');
} catch (e) { console.error(await page.evaluate(() => ({ button: document.querySelector('#play').textContent, error: document.querySelector('#error').textContent, time: document.querySelector('#time').value, media: [...document.querySelectorAll('video')].map(m => ({ t: m.currentTime, paused: m.paused, seeking: m.seeking, ready: m.readyState, duration: m.duration })) }))); throw e; } finally { await browser.close(); await rm(dir, { recursive: true, force: true }); }
